## Project information
site_name: Alma Acquisitions - Open Source
site_url: https://leidenuniversitylibrary.github.io/Alma-Acquisitions-Open-Source/
site_description: "AAOS displays your library's latest acquisitions: e-books, journals, e-journals, etc. and allows the library's employees to manage the acquisitions lists via an clear and user-friendly admin interface."

## Repository
repo_name: Alma-Acquisitions-Open-Source
repo_url: https://github.com/LeidenUniversityLibrary/Alma-Acquisitions-Open-Source
edit_uri: ''  #disables edit button

## Configuration
theme:
  name: material
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.png
  custom_dir: docs/override/
  palette:
    scheme: leidenuniv
    primary: white
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
  font:
    text: Open Sans
    code: Ubuntu

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true



nav:
  - Home: index.md
  - Getting started:
    - Introduction: introduction.md
    - Requirements: requirements.md
    - Part I - Alma Analytics: alma-analytics.md
    - Part II - Installation: installation.md
    - Part III - Creating acquisitions lists: creating-acquisitions-lists.md
    - Part IV - Customizations: customizations.md
  - More info:
    - About us: about.md
    - License: license.md

copyright: GNU General Public License v3.0 - Leiden University Libraries

## Social Media
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://www.universiteitleiden.nl
    - icon: fontawesome/brands/github-alt
      link: https://github.com/LeidenUniversityLibrary
